Repository Mergifyio/docs, pull requests merged in 2023-10, with the labels that each got.

#2349 docs(mq): fix typo in queue rules example
  src/content/merge-queue/setup.mdx
Labels: queued

#2350 docs(file-format): fix sharing link
  src/content/configuration/file-format.mdx
Labels: queued

#2351 docs(integrations): fix Jenkins link
  src/content/integrations/index.mdx
Labels: queued

#2352 docs(mq): fix link to spec checks
  src/content/workflow/actions/queue.mdx
Labels: queued

#2353 docs(security): fix mailto mail
  src/content/security.mdx
Labels: queued

#2354 docs(assign): fix link to data type
  src/content/workflow/actions/assign.mdx
Labels: queued

#2355 docs(rush): fix wrong relative link
  src/content/integrations/rush.mdx
Labels: queued

#2356 docs(automerge): fix link to config spec
  src/content/workflow/automerge.mdx
Labels: queued

#2369 ci: add missing permission to checkout code
  .github/workflows/docs-upload-gcp-temp.yaml
Labels: queued

#2368 chore(webpack): Add options to speed up local build
  gatsby-node.mjs
Labels: queued, skip changelog

#2375 docs: add Plausible integration
  gatsby-config.mjs
  package-lock.json
  package.json
Labels: queued, hotfix

#2380 docs(integrations): add CircleCI
  src/content/config.tsx
  src/content/images/integrations/circleci/logo.svg
  src/content/integrations/circleci.mdx
  src/content/integrations/index.mdx
Labels: queued

#2378 chore: clean out unused styles
  src/components/Page.jsx
  src/utils/index.jsx
Labels: queued

#2377 docs: remove pagination
  gatsby-node.mjs
  src/components/Page.jsx
  src/components/PageLayout.jsx
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/PaginationButton.jsx
  src/components/Pagination/index.jsx
Labels: queued

#2379 docs(assign): fix missing s in url
  src/content/workflow/actions/assign.mdx
Labels: queued

#2396 fix: Page title is wrongly computed
  src/components/Sidebar/SidebarNav.tsx
Labels: queued, skip changelog

#2376 feat(search): Use Algolia for advanced search
  .gitignore
  gatsby-config.mjs
  package-lock.json
  package.json
  src/components/SearchEngine/PageDetails.tsx
  src/components/SearchEngine/Results.tsx
  src/components/SearchEngine/SearchBar.tsx
  src/components/SearchEngine/types.ts
Labels: queued, skip changelog

#2400 fix(seo): Use react-helmet to put metadata in <head> tag
  gatsby-config.mjs
  package-lock.json
  package.json
  src/components/SEO/SEO.tsx
Labels: skip changelog

#2403 docs(mq): add explanation video
  gatsby-config.mjs
  package-lock.json
  package.json
  src/content/merge-queue/intro.mdx
  src/main.css
Labels: queued

#2402 docs(integration): add Buildkite
  src/content/config.tsx
  src/content/images/integrations/buildkite/github-status.png
  src/content/images/integrations/buildkite/logo.svg
  src/content/integrations/buildkite.mdx
  src/content/integrations/index.mdx
Labels: queued

#2418 docs: add more videos
  src/content/integrations/dependabot.mdx
  src/content/merge-queue/batches.mdx
  src/content/merge-queue/priority.mdx
  src/content/merge-queue/setup.mdx
  src/content/merge-queue/speculative-checks.mdx
Labels: queued

#2420 docs: add more icons
  src/content/config.tsx
  src/content/index.mdx
Labels: queued

#2419 docs: add request reviews use case
  src/content/config.tsx
  src/content/index.mdx
  src/content/workflow/actions/index.mdx
  src/content/workflow/actions/request_reviews.mdx
  src/content/workflow/request-reviews.mdx
Labels: queued

#2445 feat(seo): Generate og:image for each pages
  .gitignore
  gatsby-config.mjs
  gatsby-node.mjs
  generate-og-images.mjs
  package-lock.json
  package.json
  src/components/SEO/SEO.tsx
  static/fonts/Poppins-Light.ttf
  static/og-template.jpg
Labels: queued, skip changelog

#2457 docs: add delete head branches example
  src/content/config.tsx
  src/content/index.mdx
  src/content/workflow/actions/delete_head_branch.mdx
  src/content/workflow/delete-head-branches.mdx
Labels: queued

#2417 feat(seo): Add Open Graph metadata
  src/components/PageLayout.jsx
  src/components/SEO/SEO.tsx
Labels: queued, skip changelog

#2470 fix(seo): Open Graph attributes wrongly defined
  src/components/SEO/SEO.tsx
Labels: skip changelog

#2472 feat(seo): Add twitter specific tags for sharing
  src/components/SEO/SEO.tsx
Labels: skip changelog

#2479 fix: Hide default and deprecated column if not necessary
  src/components/OptionsTable.tsx
Labels: queued, skip changelog

#2483 docs(mq): add performance page
  src/components/MergeQueueCalculator.tsx
  src/content/config.tsx
  src/content/images/merge-queue/rcv-theorem.png
  src/content/index.mdx
  src/content/merge-queue/performance.mdx
Labels: queued

#2510 docs(integrations): add Slack integration
  src/content/config.tsx
  src/content/images/integrations/slack/logo.svg
  src/content/integrations/index.mdx
  src/content/integrations/slack.mdx
Labels: queued

#2515 docs(mq): document two-step CI
  src/content/config.tsx
  src/content/index.mdx
  src/content/merge-queue/two-step.mdx
Labels: queued

#2528 feat(search): Search and display pages tables
  gatsby-config.mjs
  gatsby-node.mjs
  package-lock.json
  package.json
  remark-headings-plugin.mjs
  src/@types/mdxast.ts
  src/components/ConfigOptions.tsx
  src/components/OptionsTable.tsx
  src/components/Page.jsx
  src/components/PullRequestAttributesTable.jsx
  src/components/SearchEngine/PageDetails.tsx
  src/components/SearchEngine/Results.tsx
  src/components/SearchEngine/SearchBar.tsx
  src/components/SearchEngine/types.ts
  src/components/mdxComponents.jsx
  src/utils/mdxast.tsx
Labels: skip changelog

#2530 fix(algolia): Replace `gatsby-plugin-algolia` by own integration
  gatsby-config.mjs
  plugins/algolia-plugin/gatsby-node.js
  plugins/algolia-plugin/package.json
  src/components/SearchEngine/Results.tsx
  src/components/SearchEngine/types.ts
Labels: queued, skip changelog

#2562 docs: fix missing space in list rendering
  src/components/ConfigOptions.tsx
Labels: queued

#2561 docs(workflow): add dismiss reviews use case
  src/content/config.tsx
  src/content/index.mdx
  src/content/workflow/actions/dismiss_reviews.mdx
  src/content/workflow/actions/index.mdx
  src/content/workflow/dismiss-reviews.mdx
Labels: queued

#2564 docs: document permissions system in Mergify
  src/content/index.mdx
  src/content/security.mdx
Labels: queued

#2575 refactor(github_actions): allow template for inputs
  src/content/workflow/actions/github_actions.mdx
  static/mergify-configuration-openapi.json
Labels: queued

#2581 docs(integrations): add GitLab
  src/content/config.tsx
  src/content/images/integrations/gitlab/logo.svg
  src/content/integrations/gitlab.mdx
  src/content/integrations/index.mdx
Labels: queued

#2592 docs: small billing adjustment
  src/content/billing.mdx
Labels: queued

#2580 docs: improve schedule configuration
  src/components/ConfigOptions.tsx
  src/content/configuration/data-types.mdx
  static/mergify-configuration-openapi.json
Labels: queued

#2579 docs(workflow): add rebase use case
  src/content/commands/_rebase_advantages.mdx
  src/content/commands/rebase.mdx
  src/content/config.tsx
  src/content/images/commands/rebase/example.png
  src/content/index.mdx
  src/content/workflow/actions/rebase.mdx
  src/content/workflow/rebase.mdx
Labels: queued

#2628 ci: upgrade node version to 20 and ubuntu to 22.04
  .github/workflows/ci.yaml
  .node-version
Labels: queued

#2627 ci: run deploy workflow on ubuntu-latest
  .github/workflows/deploy-cf.yaml
Labels: queued

#2629 docs: remove plan tags usage
  src/content/workflow/actions/merge.mdx
Labels: queued

#2626 fix: print GitHub JSON error in case something wrong happens
  static/mergify-count-active-users.py
Labels: queued

#2625 docs(action): set merge method to none by default
  static/mergify-configuration-openapi.json
Labels: queued

#2657 docs: move /merge-queue/intro to /merge-queue
  redirects.json
  src/content/commands/queue.mdx
  src/content/config.tsx
  src/content/configuration/file-format.mdx
  src/content/getting-started.mdx
  src/content/index.mdx
  src/content/integrations/snyk.mdx
  src/content/merge-queue/index.mdx
  src/content/merge-queue/setup.mdx
  src/content/workflow/actions/queue.mdx
  src/content/workflow/actions/rebase.mdx
  src/content/workflow/actions/update.mdx
  src/content/workflow/automerge.mdx
  src/content/workflow/rebase.mdx
Labels: queued

#2659 docs: fix GHA typo
  src/content/workflow/actions/github_actions.mdx
  static/mergify-configuration-openapi.json
Labels: queued

#2666 feat: Add permalink on header h2,h3...
  src/components/mdxComponents.jsx
Labels: queued, skip changelog

#2669 fix: use static openapi.json
  .github/workflows/engine-api-schemas-sync.yml
  .mergify.yml
  src/pages/api-schemas.json
  src/pages/api.tsx
Labels: queued

#2680 docs: add new attribute head-repo-full-name
  static/mergify-configuration-openapi.json
Labels: queued

#2670 chore: remove useless file
  cf-build.sh
Labels: queued

#2671 docs: create general workflow intro
  src/content/config.tsx
  src/content/configuration/file-format.mdx
  src/content/index.mdx
  src/content/workflow/delete-head-branches.mdx
  src/content/workflow/index.mdx
Labels: queued

#2690 fix(search): Fix `em` tags in boolean values
  src/utils/mdxast.tsx
Labels: queued, skip changelog

#2695 chore(csp): add algolia
  gatsby-config.mjs
Labels: queued, hotfix

#2696 fix: add missing self in connect-src
  gatsby-config.mjs
Labels: queued, hotfix

#2694 docs: remove double ending dot
  src/content/index.mdx
Labels: queued

#2711 fix(csp): add plausible.io/youtube.com and inline fonts
  gatsby-config.mjs
Labels: hotfix
