Repository Mergifyio/docs, pull requests merged in 2023-09, with the labels that each got.

#2230 docs: fix links
  src/content/configuration/file-format.mdx
  src/content/merge-queue/speculative-checks.mdx
  src/content/workflow/actions/queue.mdx
Labels: queued

#2243 fix: Duplicate key in json schema
  src/content/mergify-configuration-openapi.json
Labels: queued, skip changelog

#2233 docs(rebase): fix link
  src/content/workflow/actions/rebase.mdx
Labels: queued

#2232 docs: add link from getting started
  src/content/getting-started.mdx
Labels: queued

#2231 ci: increase timeout of docs-upload-to-gcp-prod
  .github/workflows/docs-upload-gcp-prod.yaml
Labels: queued

#2252 fix: Page title is wrong sometimes
  src/content/config.tsx
Labels: skip changelog

#2250 fix(cf): ensure Cloudflare doesn't touch the generated page
  .github/workflows/docs-upload-gcp-prod.yaml
Labels: queued

#2251 fix: Move json-schema to static folder to be served correctly
  src/components/ActionOptionsTable.tsx
  src/components/ConfigOptions.tsx
  src/components/OptionsTable.tsx
  src/components/PullRequestAttributesTable.jsx
  static/mergify-configuration-openapi.json
Labels: queued, skip changelog

#2255 docs(graphite): add link
  src/content/integrations/graphite.mdx
Labels: queued

#2257 docs(merge): add list of supported branch protections
  src/content/workflow/actions/merge.mdx
Labels: queued

#2256 docs(merge): add link to refresh
  src/content/workflow/actions/merge.mdx
Labels: queued

#2271 ci: drop upload of docs on gcp
  .github/workflows/docs-upload-gcp-prod.yaml
Labels: queued

#2270 ci: add CF Pages -> Slack notifications
  .github/workflows/deploy-cf.yaml
  cf-build.sh
  package.json
Labels: queued

#2274 docs(mq): add missing links in setup
  src/content/merge-queue/setup.mdx
Labels: queued

#2273 docs(workflow): add missing link
  src/content/workflow/writing-your-first-rule.mdx
Labels: queued

#2279 docs(billing): add email link
  src/content/billing.mdx
Labels: queued

#2281 docs(queue): add link to spec check settings
  src/content/merge-queue/speculative-checks.mdx
Labels: queued

#2284 docs(mq): fix readibility for spec checks schema
  src/content/merge-queue/speculative-checks.mdx
Labels: queued

#2285 feat: add width 100 on menu items to standardize hover effect width
  src/components/Sidebar/NavItems.jsx
Labels: queued, skip changelog

#2283 docs(mq): add schema in batches docs
  src/content/merge-queue/batches.mdx
Labels: queued

#2301 fix: add more redirects
  redirects.json
Labels: queued

#2306 chore(integrations): remove unused imports
  src/content/integrations/index.mdx
Labels: queued

#2305 docs: fix navitem external URL
  src/components/Sidebar/NavItems.jsx
Labels: queued

#2303 docs: add missing links
  src/content/merge-queue/lifecycle.mdx
  src/content/workflow/actions/update.mdx
Labels: queued

#2304 docs: add missing entries in integration index
  src/content/integrations/dependabot.mdx
  src/content/integrations/gha.mdx
  src/content/integrations/index.mdx
  src/content/integrations/teamcity.mdx
Labels: queued

#2320 docs: add home icon
  src/content/config.tsx
Labels: queued

#2319 docs(security): add bug bounty
  src/content/security.mdx
Labels: queued

#2316 docs(mq): add deployment page
  src/content/config.tsx
  src/content/images/merge-queue/deploy/bp-rule.png
  src/content/images/merge-queue/deploy/bp-settings.png
  src/content/index.mdx
  src/content/merge-queue/deploy.mdx
Labels: queued

#2318 docs(rebase): document hidden features
  src/content/commands/rebase.mdx
Labels: queued

#2317 docs(integration): add rush
  src/content/config.tsx
  src/content/images/integrations/rush/logo.svg
  src/content/integrations/index.mdx
  src/content/integrations/rush.mdx
Labels: queued

#2335 ci: add .node-version
  .node-version
Labels: queued

#2339 ci: remove usage of secrets.GCP_DOCS_CREDENTIAL_JSON
  .github/workflows/docs-upload-gcp-temp.yaml
Labels: queued
