Repository Mergifyio/docs, pull requests merged in 2023-11, with the labels that each got.

#2693 docs(mq): add pause feature
  src/content/config.tsx
  src/content/images/merge-queue/pause/dashboard-button-pause-mq.png
  src/content/index.mdx
  src/content/merge-queue/pause.mdx
Labels: queued

#2719 docs: add missing description for TimestampOrTimestampInterval
  static/mergify-configuration-openapi.json
Labels: queued

#2727 docs(post_check): document neutral_conditions
  static/mergify-configuration-openapi.json
Labels: queued

#2743 docs(config): allow null value for checks_timeout
  src/components/ConfigOptions.tsx
  static/mergify-configuration-openapi.json
Labels: queued

#2762 docs(queue): allow null for batch_max_failure_resolution_attempts
  static/mergify-configuration-openapi.json
Labels: queued

#2763 docs: add queue-dequeue-reason
  src/components/ConfigOptions.tsx
  src/content/configuration/data-types.mdx
  static/mergify-configuration-openapi.json
Labels: queued

#2775 fix(openapi): Override dark mode colors in api reference
  src/pages/api.tsx
  src/pages/dark-mode-override.css
Labels: skip changelog

#2776 fix: use oneOf and not anyOf
  static/mergify-configuration-openapi.json
Labels: queued

#2777 fix(api-reference): Wrong selectors for dark mode overrides
  src/pages/dark-mode-override.css
Labels: queued, skip changelog, hotfix

#2794 fix(css): Add missing parent selector in dark mode overrides
  src/pages/api.tsx
  src/pages/dark-mode-override.css
Labels: skip changelog, hotfix

#2809 docs(dequeue): rename from unqueue
  redirects.json
  src/content/commands/dequeue.mdx
  src/content/commands/index.mdx
  src/content/config.tsx
  src/content/configuration/data-types.mdx
  src/content/merge-queue/lifecycle.mdx
  static/mergify-configuration-openapi.json
Labels: queued

#2795 docs: add custom branch protection examples
  src/content/config.tsx
  src/content/index.mdx
  src/content/workflow/actions/post_check.mdx
  src/content/workflow/automerge.mdx
  src/content/workflow/custom-branch-protections.mdx
Labels: queued

#2846 docs(mq): tweak a few things in batch and add timeout setting
  src/content/merge-queue/batches.mdx
Labels: queued

#2845 docs: move performance before spec/batch/two-steps
  src/content/config.tsx
  src/content/index.mdx
Labels: queued

#2844 docs(mq): move paragraph on spec check below
  src/content/merge-queue/batches.mdx
Labels: queued

#2866 docs(mq): explain how to keep labels on draft PRs
  src/content/merge-queue/_mergify-merge-queue-labels-copier.mdx
  src/content/merge-queue/batches.mdx
  src/content/merge-queue/speculative-checks.mdx
Labels: queued

#2894 docs: rename queue-partition-name to partition-name
  src/content/integrations/rush.mdx
  src/content/merge-queue/partitions.mdx
  static/mergify-configuration-openapi.json
Labels: queued

#2905 docs(mq): document how to merge a single batch
  src/content/images/merge-queue/batches/mergify-required-pull-request-bypass.png
  src/content/merge-queue/batches.mdx
  src/content/merge-queue/speculative-checks.mdx
Labels: queued

#2949 fix(github): fix the sync of API schemas
  .github/workflows/engine-api-schemas-sync.yml
Labels: hotfix
