Repository Mergifyio/docs, pull requests merged in 2024-01, with the labels that each got.

#3146 fix(sidebar): Missing padding on nav items in production
  src/components/LeftSidebar/NavGroup.astro
Labels: skip changelog, hotfix

#3149 fix: readd the Gatsby service worker
  public/sw.js
Labels: queued, hotfix

#3148 ci: only set SITE_URL for preview branches
  cf-build.sh
Labels: queued

#3152 chore: add a note about sw.js
  public/sw.js
Labels: queued

#3153 docs: add enum for queue_branch_merge_method
  public/mergify-configuration-openapi.json
Labels: queued

#3182 docs: fix link to regular expression
  src/content/docs/configuration/conditions.mdx
Labels: queued

#3195 fix: sort configuration table by names
  src/components/Tables/PullRequestAttributes.tsx
Labels: queued

#3184 ci: change where api-schemas.json is stored
  .github/workflows/engine-api-schemas-sync.yml
Labels: queued

#3230 fix: Remove override env var
  astro.config.ts
Labels: skip changelog

#3296 fix: Anchor link is hard to click on
  src/styles/index.css
Labels: skip changelog

#3308 docs(refactor): remove and update doc for allow_merging_conf_change
  public/mergify-configuration-openapi.json
  src/content/docs/workflow/actions/merge.mdx
  src/content/images/workflow/actions/merge/branch-protections-injection.png
Labels: queued

#3310 fix: Fix all broken links on docs
  src/content/docs/configuration/conditions.mdx
  src/content/docs/configuration/data-types.mdx
  src/content/docs/configuration/file-format.mdx
  src/content/docs/configuration/sharing.mdx
  src/content/docs/merge-queue/batches.mdx
  src/content/docs/merge-queue/freeze.mdx
  src/content/docs/merge-queue/index.mdx
  src/content/docs/merge-queue/lifecycle.mdx
  src/content/docs/merge-queue/multi.mdx
  src/content/docs/merge-queue/pause.mdx
  src/content/docs/merge-queue/performance.mdx
  src/content/docs/merge-queue/priority.mdx
  src/content/docs/merge-queue/setup.mdx
  src/content/docs/merge-queue/troubleshooting.mdx
  src/content/docs/merge-queue/two-step.mdx
  src/content/docs/workflow/actions/copy.mdx
  src/content/docs/workflow/actions/merge.mdx
  src/content/docs/workflow/automerge.mdx
  src/content/docs/workflow/custom-branch-protections.mdx
Labels: queued, skip changelog

#3312 docs: add documentation for YAML anchor extend feature
  src/content/docs/configuration/sharing.mdx
Labels: queued
