Repository Mergifyio/docs, pull requests merged in 2024-09, with the labels that each got.

#5054 refactor(config): switch to $defs root key for definition
  plugins/remark-algolia.ts
  public/mergify-configuration-schema.json
  src/components/Tables/ActionOptionsTable.tsx
  src/components/Tables/OptionsTable.tsx
  src/components/Tables/PullRequestAttributes.tsx
Labels: queued

#5077 docs: do not talk about rebase in update
  src/content/docs/workflow/actions/update.mdx
Labels: queued

#5099 docs: fix missing type description
  src/components/Tables/ConfigOptions.tsx
Labels: queued, hotfix, ignore-broken-links

#5114 docs: add configuration changed doc for merge protections
  src/content/docs/merge-protections/index.mdx
  src/content/images/merge-protections/configuration-changed-check.png
Labels: queued, ignore-broken-links

#5103 docs: document the deprecation of `allow_checks_interruption` in `queue_rules`
  public/mergify-configuration-schema.json
Labels: queued, ignore-broken-links

#5168 docs: remove unused valueType field in option definition
  src/components/Tables/ConfigOptions.tsx
Labels: queued

#5184 fix: upgrade astro
  package-lock.json
Labels: hotfix

#5210 refactor(config): use recursive type description
  src/components/Tables/ConfigOptions.tsx
Labels: queued

#5211 refactor: switch action and types to new configuration
  plugins/remark-algolia.ts
  src/components/Tables/ActionOptionsTable.tsx
  src/components/Tables/ConfigOptions.tsx
  src/components/Tables/OptionsTable.tsx
  src/components/Tables/PullRequestAttributes.tsx
  src/content/docs/commands/restrictions.mdx
  src/content/docs/configuration/data-types.mdx
  src/content/docs/configuration/file-format.mdx
  src/content/docs/merge-queue/partitions.mdx
  src/content/docs/merge-queue/priority.mdx
  src/content/docs/workflow/actions/assign.mdx
  src/content/docs/workflow/actions/backport.mdx
  src/content/docs/workflow/actions/close.mdx
  src/content/docs/workflow/actions/comment.mdx
  src/content/docs/workflow/actions/copy.mdx
  src/content/docs/workflow/actions/delete_head_branch.mdx
  src/content/docs/workflow/actions/dismiss_reviews.mdx
  src/content/docs/workflow/actions/edit.mdx
  src/content/docs/workflow/actions/github_actions.mdx
  src/content/docs/workflow/actions/label.mdx
  src/content/docs/workflow/actions/merge.mdx
  src/content/docs/workflow/actions/post_check.mdx
  src/content/docs/workflow/actions/queue.mdx
  src/content/docs/workflow/actions/rebase.mdx
  src/content/docs/workflow/actions/request_reviews.mdx
  src/content/docs/workflow/actions/review.mdx
  src/content/docs/workflow/actions/squash.mdx
  src/content/docs/workflow/actions/update.mdx
Labels: queued

#5249 fix: add new font provider
  public/_headers
Labels: queued, hotfix

#5254 fix(algolia): wrong key when adding custom table options
  plugins/remark-algolia.ts
Labels: hotfix
