Repository Mergifyio/docs, pull requests merged in 2024-03, with the labels that each got.

#3656 docs: add documentation for `report_mode` on copy and backport action
  public/mergify-configuration-openapi.json
  src/components/Tables/ConfigOptions.tsx
  src/content/docs/configuration/data-types.mdx
Labels: queued

#3759 ci: fix Cloudflare pages CI name
  .mergify.yml
Labels: hotfix

#3754 docs: fix link to bug bounty
  src/content/docs/security.mdx
Labels: queued

#3755 refactor(schema): Remove $id from all definitions
  public/mergify-configuration-openapi.json
  src/components/Tables/ConfigOptions.tsx
Labels: queued

#3756 fix(schema): Disallow additional properties
  public/mergify-configuration-openapi.json
Labels: queued

#3780 fix(schema): Add missing `additionalProperties: false` on actions
  public/mergify-configuration-openapi.json
Labels: skip changelog

#3783 docs: add {added,modified,deleted}-lines
  public/mergify-configuration-openapi.json
Labels: queued

#3798 docs(config): update default values for copy and backport bodies
  public/mergify-configuration-openapi.json
Labels: queued

#3797 chore: remove non working job
  .github/workflows/mergify-configuration-openapi-spec-sync.yml
Labels: queued

#3799 ci: drop unused workflow job
  .github/workflows/engine-api-schemas-sync.yml
Labels: queued
